name: deploy

runs:
  using: "composite"
  steps:
    - name: Docker pull image
      run: |
        echo "docker login --username ${CI_REGISTRY_USER} --password ${CI_REGISTRY_PASSWORD}"
        echo "docker pull ${CI_REGISTRY_IMAGE}:${PULL_REQUEST_SHA}"
        echo "docker-compose up"
      env:
        PULL_REQUEST_SHA: ${{ github.event.pull_request.head.sha }}
        CI_REGISTRY_IMAGE: ${{ env.CI_REGISTRY_IMAGE }}
        CI_REGISTRY_USER: ${{ env.CI_REGISTRY_USER }}
        CI_REGISTRY_PASSWORD: ${{ env.CI_REGISTRY_PASSWORD }}