name: deploy

runs:
  using: "composite"
  steps:
    - name: Docker login
      run: echo "docker login --username ${{ secrets.CI_REGISTRY_USER }} --password ${{ secrets.CI_REGISTRY_PASSWORD }}"
    - name: Pull from Hub
      run: echo "docker pull ${{ secrets.CI_REGISTRY_IMAGE }}:${{ github.event.pull_request.head.sha }}"
    - name: Run app container
      run: echo "docker-compose up"