name: main

on:
  pull_request:
    types: [opened, closed]
    branches:
      - master
      - alpha

jobs:
  build:
    runs-on: [self-hosted, stage]
    if: github.event.pull_request.merged == false
    environment: stage
    steps:
      - uses: actions/checkout@v3
      - name: Docker login
        run: echo "docker login --username ${{ secrets.CI_REGISTRY_USER }} --password ${{ secrets.CI_REGISTRY_PASSWORD }}"
      - name: Build container
        run: echo "docker build -t ${{ secrets.CI_REGISTRY_IMAGE }}:${{ github.event.pull_request.head.sha }} ."
      - name: Push to Hub
        run: echo "docker push ${{ secrets.CI_REGISTRY_IMAGE }}:${{ github.event.pull_request.head.sha }}"

  stage:
    runs-on: [self-hosted, stage]
    environment: stage
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - uses: CaptainOmega/test-github-workflows/.github/actions/deploy@master

  test:
    runs-on: [self-hosted, stage]
    environment: stage
    needs: [stage]
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: echo "npm run e2e"
  
  alpha:
    runs-on: [self-hosted, alpha]
    environment: alpha
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'alpha'
    steps:
      - uses: actions/checkout@v3
      - uses: CaptainOmega/test-github-workflows/.github/actions/deploy@master

  prod:
    runs-on: [self-hosted, prod]
    environment: prod
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'master'
    steps:
      - uses: actions/checkout@v3
      - uses: CaptainOmega/test-github-workflows/.github/actions/deploy@master